### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Tn5871** [kordk/torch-ecpg#39]
Hi, when I try to install the package using the "pip install git+https://github.com/kordk/torch-ecpg.git" command, I get the following error:

Collecting git+https://github.com/kordk/torch-ecpg.git
  Cloning https://github.com/kordk/torch-ecpg.git to /tmp/pip-req-build-gpalenfs
  Running command git clone -q https://github.com/kordk/torch-ecpg.git /tmp/pip-req-build-gpalenfs
    ERROR: Command errored out with exit status 1:
     command: /home/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-gpalenfs/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-gpalenfs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-szamn4f2
         cwd: /tmp/pip-req-build-gpalenfs/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-gpalenfs/setup.py", line 15, in <module>
        requirements = [line.removesuffix('\n') for line in file.readlines()]
      File "/tmp/pip-req-build-gpalenfs/setup.py", line 15, in <listcomp>
        requirements = [line.removesuffix('\n') for line in file.readlines()]
    AttributeError: 'str' object has no attribute 'removesuffix'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by kordk** [comment]
What version of Python are you using?

**Comment by liamgd** [comment]
The string removesuffix method was added in [PEP 616](https://peps.python.org/pep-0616/) as a part of Python 3.9. The program was built on Python 3.10 and is likely compatible with 3.11 and 3.12. Upgrade to one of these versions and try to reinstall the package. I hope this helps.
